//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package www.bn.simm.ws.open.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the www.bn.simm.ws.open.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: www.bn.simm.ws.open.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTns1RptaListaEnvioCorreos }
     * 
     */
    public ArrayOfTns1RptaListaEnvioCorreos createArrayOfTns1RptaListaEnvioCorreos() {
        return new ArrayOfTns1RptaListaEnvioCorreos();
    }

    /**
     * Create an instance of {@link ArrayOfTns1ReqListMessage }
     * 
     */
    public ArrayOfTns1ReqListMessage createArrayOfTns1ReqListMessage() {
        return new ArrayOfTns1ReqListMessage();
    }

}
