//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package www.bn.simm.ws.open.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosParametro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosParametro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parametro1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro13" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro14" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro15" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro16" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro17" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro18" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro19" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosParametro", propOrder = {
    "parametro1",
    "parametro10",
    "parametro11",
    "parametro12",
    "parametro13",
    "parametro14",
    "parametro15",
    "parametro16",
    "parametro17",
    "parametro18",
    "parametro19",
    "parametro2",
    "parametro3",
    "parametro4",
    "parametro5",
    "parametro6",
    "parametro7",
    "parametro8",
    "parametro9"
})
public class DatosParametro {

    @XmlElement(required = true, nillable = true)
    protected String parametro1;
    @XmlElement(required = true, nillable = true)
    protected String parametro10;
    @XmlElement(required = true, nillable = true)
    protected String parametro11;
    @XmlElement(required = true, nillable = true)
    protected String parametro12;
    @XmlElement(required = true, nillable = true)
    protected String parametro13;
    @XmlElement(required = true, nillable = true)
    protected String parametro14;
    @XmlElement(required = true, nillable = true)
    protected String parametro15;
    @XmlElement(required = true, nillable = true)
    protected String parametro16;
    @XmlElement(required = true, nillable = true)
    protected String parametro17;
    @XmlElement(required = true, nillable = true)
    protected String parametro18;
    @XmlElement(required = true, nillable = true)
    protected String parametro19;
    @XmlElement(required = true, nillable = true)
    protected String parametro2;
    @XmlElement(required = true, nillable = true)
    protected String parametro3;
    @XmlElement(required = true, nillable = true)
    protected String parametro4;
    @XmlElement(required = true, nillable = true)
    protected String parametro5;
    @XmlElement(required = true, nillable = true)
    protected String parametro6;
    @XmlElement(required = true, nillable = true)
    protected String parametro7;
    @XmlElement(required = true, nillable = true)
    protected String parametro8;
    @XmlElement(required = true, nillable = true)
    protected String parametro9;

    /**
     * Gets the value of the parametro1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro1() {
        return parametro1;
    }

    /**
     * Sets the value of the parametro1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro1(String value) {
        this.parametro1 = value;
    }

    /**
     * Gets the value of the parametro10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro10() {
        return parametro10;
    }

    /**
     * Sets the value of the parametro10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro10(String value) {
        this.parametro10 = value;
    }

    /**
     * Gets the value of the parametro11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro11() {
        return parametro11;
    }

    /**
     * Sets the value of the parametro11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro11(String value) {
        this.parametro11 = value;
    }

    /**
     * Gets the value of the parametro12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro12() {
        return parametro12;
    }

    /**
     * Sets the value of the parametro12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro12(String value) {
        this.parametro12 = value;
    }

    /**
     * Gets the value of the parametro13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro13() {
        return parametro13;
    }

    /**
     * Sets the value of the parametro13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro13(String value) {
        this.parametro13 = value;
    }

    /**
     * Gets the value of the parametro14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro14() {
        return parametro14;
    }

    /**
     * Sets the value of the parametro14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro14(String value) {
        this.parametro14 = value;
    }

    /**
     * Gets the value of the parametro15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro15() {
        return parametro15;
    }

    /**
     * Sets the value of the parametro15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro15(String value) {
        this.parametro15 = value;
    }

    /**
     * Gets the value of the parametro16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro16() {
        return parametro16;
    }

    /**
     * Sets the value of the parametro16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro16(String value) {
        this.parametro16 = value;
    }

    /**
     * Gets the value of the parametro17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro17() {
        return parametro17;
    }

    /**
     * Sets the value of the parametro17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro17(String value) {
        this.parametro17 = value;
    }

    /**
     * Gets the value of the parametro18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro18() {
        return parametro18;
    }

    /**
     * Sets the value of the parametro18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro18(String value) {
        this.parametro18 = value;
    }

    /**
     * Gets the value of the parametro19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro19() {
        return parametro19;
    }

    /**
     * Sets the value of the parametro19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro19(String value) {
        this.parametro19 = value;
    }

    /**
     * Gets the value of the parametro2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro2() {
        return parametro2;
    }

    /**
     * Sets the value of the parametro2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro2(String value) {
        this.parametro2 = value;
    }

    /**
     * Gets the value of the parametro3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro3() {
        return parametro3;
    }

    /**
     * Sets the value of the parametro3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro3(String value) {
        this.parametro3 = value;
    }

    /**
     * Gets the value of the parametro4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro4() {
        return parametro4;
    }

    /**
     * Sets the value of the parametro4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro4(String value) {
        this.parametro4 = value;
    }

    /**
     * Gets the value of the parametro5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro5() {
        return parametro5;
    }

    /**
     * Sets the value of the parametro5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro5(String value) {
        this.parametro5 = value;
    }

    /**
     * Gets the value of the parametro6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro6() {
        return parametro6;
    }

    /**
     * Sets the value of the parametro6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro6(String value) {
        this.parametro6 = value;
    }

    /**
     * Gets the value of the parametro7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro7() {
        return parametro7;
    }

    /**
     * Sets the value of the parametro7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro7(String value) {
        this.parametro7 = value;
    }

    /**
     * Gets the value of the parametro8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro8() {
        return parametro8;
    }

    /**
     * Sets the value of the parametro8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro8(String value) {
        this.parametro8 = value;
    }

    /**
     * Gets the value of the parametro9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametro9() {
        return parametro9;
    }

    /**
     * Sets the value of the parametro9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametro9(String value) {
        this.parametro9 = value;
    }

}
