//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package www.bn.simm.ws.open.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosCorreo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosCorreo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asunto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correoCopia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correoDestinatario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correoOculto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosCorreo", propOrder = {
    "asunto",
    "correoCopia",
    "correoDestinatario",
    "correoOculto"
})
public class DatosCorreo {

    @XmlElement(required = true, nillable = true)
    protected String asunto;
    @XmlElement(required = true, nillable = true)
    protected String correoCopia;
    @XmlElement(required = true, nillable = true)
    protected String correoDestinatario;
    @XmlElement(required = true, nillable = true)
    protected String correoOculto;

    /**
     * Gets the value of the asunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsunto() {
        return asunto;
    }

    /**
     * Sets the value of the asunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsunto(String value) {
        this.asunto = value;
    }

    /**
     * Gets the value of the correoCopia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreoCopia() {
        return correoCopia;
    }

    /**
     * Sets the value of the correoCopia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreoCopia(String value) {
        this.correoCopia = value;
    }

    /**
     * Gets the value of the correoDestinatario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreoDestinatario() {
        return correoDestinatario;
    }

    /**
     * Sets the value of the correoDestinatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreoDestinatario(String value) {
        this.correoDestinatario = value;
    }

    /**
     * Gets the value of the correoOculto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreoOculto() {
        return correoOculto;
    }

    /**
     * Sets the value of the correoOculto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreoOculto(String value) {
        this.correoOculto = value;
    }

}
