//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package www.bn.simm.ws.open.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the www.bn.simm.ws.open.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: www.bn.simm.ws.open.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestMessage }
     * 
     */
    public RequestMessage createRequestMessage() {
        return new RequestMessage();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link DatosCorreo }
     * 
     */
    public DatosCorreo createDatosCorreo() {
        return new DatosCorreo();
    }

    /**
     * Create an instance of {@link ReqListMessage }
     * 
     */
    public ReqListMessage createReqListMessage() {
        return new ReqListMessage();
    }

    /**
     * Create an instance of {@link DatosParametro }
     * 
     */
    public DatosParametro createDatosParametro() {
        return new DatosParametro();
    }

    /**
     * Create an instance of {@link Adjunto }
     * 
     */
    public Adjunto createAdjunto() {
        return new Adjunto();
    }

    /**
     * Create an instance of {@link RptaListaEnvioCorreos }
     * 
     */
    public RptaListaEnvioCorreos createRptaListaEnvioCorreos() {
        return new RptaListaEnvioCorreos();
    }

}
