//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package www.bn.simm.ws.open.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import www.bn.simm.ws.open.service.ArrayOfTns1RptaListaEnvioCorreos;


/**
 * <p>Java class for ResponseMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codComunicacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codRetorno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nroRegistrosError" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nroRegistrosOk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rptaListaEnvioCorreos" type="{http://service.open.ws.simm.bn.www}ArrayOf_tns1_RptaListaEnvioCorreos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseMessage", propOrder = {
    "codComunicacion",
    "codRetorno",
    "nroRegistrosError",
    "nroRegistrosOk",
    "rptaListaEnvioCorreos"
})
public class ResponseMessage {

    @XmlElement(required = true, nillable = true)
    protected String codComunicacion;
    @XmlElement(required = true, nillable = true)
    protected String codRetorno;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer nroRegistrosError;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer nroRegistrosOk;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns1RptaListaEnvioCorreos rptaListaEnvioCorreos;

    /**
     * Gets the value of the codComunicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodComunicacion() {
        return codComunicacion;
    }

    /**
     * Sets the value of the codComunicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodComunicacion(String value) {
        this.codComunicacion = value;
    }

    /**
     * Gets the value of the codRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodRetorno() {
        return codRetorno;
    }

    /**
     * Sets the value of the codRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodRetorno(String value) {
        this.codRetorno = value;
    }

    /**
     * Gets the value of the nroRegistrosError property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNroRegistrosError() {
        return nroRegistrosError;
    }

    /**
     * Sets the value of the nroRegistrosError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNroRegistrosError(Integer value) {
        this.nroRegistrosError = value;
    }

    /**
     * Gets the value of the nroRegistrosOk property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNroRegistrosOk() {
        return nroRegistrosOk;
    }

    /**
     * Sets the value of the nroRegistrosOk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNroRegistrosOk(Integer value) {
        this.nroRegistrosOk = value;
    }

    /**
     * Gets the value of the rptaListaEnvioCorreos property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns1RptaListaEnvioCorreos }
     *     
     */
    public ArrayOfTns1RptaListaEnvioCorreos getRptaListaEnvioCorreos() {
        return rptaListaEnvioCorreos;
    }

    /**
     * Sets the value of the rptaListaEnvioCorreos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns1RptaListaEnvioCorreos }
     *     
     */
    public void setRptaListaEnvioCorreos(ArrayOfTns1RptaListaEnvioCorreos value) {
        this.rptaListaEnvioCorreos = value;
    }

}
